apiVersion: v1
kind: Service
metadata:
  name: fleetlock
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
spec:
  type: ClusterIP
  clusterIP: 10.3.0.15
  selector:
    name: fleetlock
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

